name: Create Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/maven.yml

  release:
    needs:
      - build

    runs-on: ubuntu-latest

    if: ${{ github.ref_name == 'master' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zone-relay
          path: artifact

      - name: Copy files
        run: |
          mkdir release
          cp -p artifact/*.exe release
          cp -a data/ release
          cp -a locales/ release
          cp -a resources/ release

      - name: Create archive
        run: zip -r ZoneRelay-${{ inputs.build-ver }}.zip .
        working-directory: release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.build-ver }}
          name: Release ${{ inputs.build-ver }}
          body_path: ./CHANGELOG.md
          prerelease: false
          files: release/ZoneRelay-${{ inputs.build-ver }}.zip
